name: Run Tests and Upload Coverage

on:
  workflow_call:
  
env:
  TEST_RESULTS: .build/TestResults/Result.xcresult

jobs:
  run-tests-and-upload-coverage:
    name: "Run Tests and Upload Coverage"
    runs-on: macos-12
    
    strategy:
      matrix:
        platform: [iOS, iPad]
        include:
          - platform: iOS
            sdk: iphonesimulator
            destination: "name=iPhone 14"

          - platform: iPad
            sdk: iphonesimulator
            destination: "name=iPad Pro (12.9-inch) (5th generation)"

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '14.0'
        
    - name: Generate Xcode Project
      run: swift package generate-xcodeproj
        
    - name: Run Tests
      uses: sersoft-gmbh/xcodebuild-action@v1
      with:
        action: test
        project: UIKitExtensions.xcodeproj
        scheme: UIKitExtensions-Package
        sdk: ${{ matrix.sdk }}
        destination: "${{ matrix.destination }}"
        enable-code-coverage: true
        result-bundle-path: ${{ env.TEST_RESULTS }}
        derived-data-path: .build
        use-xcpretty: true
      
    - name: Upload Coverage Data to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
        xcode: true
        xcode_archive_path: ${{ env.TEST_RESULTS }}
