name: Tests On Pull Request

on:
  pull_request:
    branches: [ dev ]

jobs:
  run-tests-and-upload-coverage:
    uses: dsk1306/uikitExtensions/.github/workflows/run-tests-and-upload-coverage.yml@actions
    secrets: inherit
