name: Tests On Push

on:
  push:
    branches: [ dev ]

jobs:
  run-tests-and-upload-coverage:
    uses: dsk1306/uikitExtensions/.github/workflows/run-tests-and-upload-coverage.yml@dev
    secrets: inherit
